name         'bison-upstart'
version      '0.0.1'
source       'git://github.com/bison/puppet-upstart.git'
author       'Brad Ison'
license      'Apache License Version 2.0'
summary      'Puppet Upstart module'
description  'This module manages Upstart job configurations'
project_page 'https://github.com/bison/puppet-upstart'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
